name: mi-lib_build
on:
  schedule:
    - cron: '0 0 */1 * *'
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Imstall MiLib
        run: |
          git clone git@github.com:mi-lib/mi-lib-starter.git
          cd mi-lib-starter
          ./scripts/mi-lib-install

